### ISSUE TITLE
[Bug]  chrash afzer trying to see saved music

### ISSUE THREAD

**Issue by 1mike10** [gokadzev/Musify#252]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

Whan i open "local music" the app chrashes.

### Expected Behavior

It should show my music

### Musify Version

5.4.0

### Operating System Version

Android 8

**Comment by gokadzev** [comment]
@1mike10 It doesn't crash on Android 11-12-13. so I need logs to see what's happening in Android 8 case.

**Comment by 1mike10** [comment]
> @1mike10 It doesn't crash on Android 11-12-13. so I need logs to see what's happening in Android 8 case.

How do i send logs

**Comment by gokadzev** [comment]
> > @1mike10 It doesn't crash on Android 11-12-13. so I need logs to see what's happening in Android 8 case.
> 
> @gokadzev How do i send logs

It's possible with adb if you have pc or using rooted device. (details here: https://github.com/gokadzev/Musify/issues/170#issuecomment-1452765058)

**Comment by 1mike10** [comment]
@gokadzev where is dev

**Comment by gokadzev** [comment]
> @gokadzev "6. Send txt file to dev." where is dev

I'm the dev 😄 you can send the file here

**Comment by 1mike10** [comment]
Ok i will send it later.
And im sorry i mismatched I have android 9 but Samsung note 8😅

**Comment by gokadzev** [comment]
> Ok i will send it later. And im sorry i mismatched I have android 9 but Samsung note 8sweat_smile

It's okay, as soon as i get logs, I try to find out what's the problem :)

**Comment by 1mike10** [comment]
[logs.txt](https://github.com/gokadzev/Musify/files/11830910/logs.txt)

**Comment by gokadzev** [comment]
Will you be able to do the same but with provided debug apk? I checked these logs and I think because of release/production build, it doesn't show exact problem.

**Comment by 1mike10** [comment]
How

**Comment by gokadzev** [comment]
> How

Download this build, and take logs again using this build (Don't forget to uninstall current installed build): https://github.com/gokadzev/Musify/releases/download/5.4.0/Musify-debug.apk

**Comment by 1mike10** [comment]
sorry for the long wait time 
[logs1.txt](https://github.com/gokadzev/Musify/files/11895127/logs1.txt)

**Comment by gokadzev** [comment]
> sorry for the long wait time [logs1.txt](https://github.com/gokadzev/Musify/files/11895127/logs1.txt)

I will review these logs anyway, but it shows the F-Droid version in the logs. However, I provided you with the normal (GitHub) version of the debug APK earlier. Are you sure you took the logs from the correct APK file?

**Comment by 1mike10** [comment]
Yea

**Comment by gokadzev** [comment]
Okay, I think I found something, It's about one of the app packages (I will note it here):


``` java 
5:20:19.489 28811 28811 E AndroidRuntime: FATAL EXCEPTION: main
06-28 15:20:19.489 28811 28811 E AndroidRuntime: Process: com.gokadzev.musify, PID: 28811
06-28 15:20:19.489 28811 28811 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property query has not been initialized
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at com.lucasjosino.on_audio_query.methods.queries.ArtworkQuery$queryArtwork$1.invokeSuspend(ArtworkQuery.kt:113)
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
06-28 15:20:19.489 28811 28811 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by marcossmtp** [comment]
It's the same for me with a samsung s7 with android 8. It crash with local.
Could I propose something?
It's not possible to add a section where the user can create his playlists?

**Comment by gokadzev** [comment]
@marcossmtp @1mike10 package repository where you can open a issue about this: https://github.com/LucJosin/on_audio_query/tree/main/packages/on_audio_query

(You can use above noted logs for more clarification too)

**Comment by OmarSaidIbrahim** [comment]
I have the same issue for android 9

**Comment by gokadzev** [comment]
> I have the same issue for android 9

@OmarSaidIbrahim @marcossmtp @1mike10, Can you check if this issue is still active in the latest version?

**Comment by OmarSaidIbrahim** [comment]
Am I able to see the fix if I download it from izzyOnDroid ?

**Comment by OmarSaidIbrahim** [comment]
Fixed for mee to, thank you so much
