### ISSUE TITLE
[Bug] ForegroundServiceStartNotAllowedException 

### ISSUE THREAD

**Issue by gokadzev** [gokadzev/Musify#479]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

Audio playing is stopped soon as app works on background (specifically not closing it totally but just moving on another apps)

### Expected Behavior

It should continue playing, no matter what

### Steps To Reproduce

- Open Musify
- Play any song
- Move wherever you want except Musify
- Wait

### Musify Version

v9.0.2

### Device And Operating System

Android 15

### Android Version You Use

Android 15

### Additional Information

```bash
W/System.err( 9587): android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.gokadzev.musify.debug/com.ryanheise.audioservice.AudioService
W/System.err( 9587): 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
W/System.err( 9587): 	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
W/System.err( 9587): 	at android.os.Parcel.readParcelableInternal(Parcel.java:5064)
W/System.err( 9587): 	at android.os.Parcel.readParcelable(Parcel.java:5046)
W/System.err( 9587): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3226)
W/System.err( 9587): 	at android.os.Parcel.createException(Parcel.java:3215)
W/System.err( 9587): 	at android.os.Parcel.readException(Parcel.java:3198)
W/System.err( 9587): 	at android.os.Parcel.readException(Parcel.java:3140)
W/System.err( 9587): 	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6393)
W/System.err( 9587): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2012)
W/System.err( 9587): 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1987)
W/System.err( 9587): 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:853)
W/System.err( 9587): 	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1128)
W/System.err( 9587): 	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:700)
W/System.err( 9587): 	at com.ryanheise.audioservice.AudioService.enterPlayingState(AudioService.java:717)
W/System.err( 9587): 	at com.ryanheise.audioservice.AudioService.setState(AudioService.java:571)
W/System.err( 9587): 	at com.ryanheise.audioservice.AudioServicePlugin$AudioHandlerInterface.onMethodCall(AudioServicePlugin.java:915)
W/System.err( 9587): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
W/System.err( 9587): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
W/System.err( 9587): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/System.err( 9587): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
W/System.err( 9587): 	at android.os.Handler.handleCallback(Handler.java:991)
W/System.err( 9587): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 9587): 	at android.os.Looper.loopOnce(Looper.java:232)
W/System.err( 9587): 	at android.os.Looper.loop(Looper.java:317)
W/System.err( 9587): 	at android.app.ActivityThread.main(ActivityThread.java:8787)
W/System.err( 9587): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9587): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
W/System.err( 9587): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)

```

**Comment by gokadzev** [comment]
I'm interested in if it's Android 15 specific bug or anyone else faces it as well.
