### ISSUE TITLE
[Bug] Some songs don't play

### ISSUE THREAD

**Issue by gokadzev** [gokadzev/Musify#482]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

some songs fail to play 

### Expected Behavior

every song should be available to be played

### Musify Version

V9.0.3

### Device And Operating System

Android 15

### Android Version You Use

Android 15

### Additional Information

logs:

```bash

I/flutter ( 7455): [2024-12-29 16:34:09.923711] Error while getting song streaming URL:UnimplementedError: Unknown unary operator: typeof
I/flutter ( 7455): #0      StreamClient.getManifest (package:youtube_explode_dart/src/videos/streams/stream_client.dart:116:7)
I/flutter ( 7455): <asynchronous suspension>
I/flutter ( 7455): #1      getAudioUrl (package:musify/API/musify.dart:673:20)
I/flutter ( 7455): <asynchronous suspension>
I/flutter ( 7455): #2      getSong (package:musify/API/musify.dart:656:12)
I/flutter ( 7455): <asynchronous suspension>
I/flutter ( 7455): #3      MusifyAudioHandler.playSong (package:musify/services/audio_service.dart:255:13)
I/flutter ( 7455): <asynchronous suspension>
I/flutter ( 7455): #4      MusifyAudioHandler.playPlaylistSong (package:musify/services/audio_service.dart:272:5)
I/flutter ( 7455): <asynchronous suspension>
I/flutter ( 7455): 

```

**Comment by gokadzev** [comment]
No idea what's happening. now in release build nothing is playing.
